cc_test(
    name = 'skip_list_test',
    srcs = 'skip_list_test.cpp',
    deps = [
        '//components/util:arena',
        '//components/util:env',
        '//components/util:hash',
        '//thirdparty/glog:glog',
        '//thirdparty/gtest:gtest',
    ]
)
