cc_library(
    name = 'cache',
    srcs = 'cache.cpp',
    deps = [
    ],
)

cc_test(
    name = 'cache_test',
    srcs = 'cache_test.cpp',
    deps = [
        ':cache',
        '//components/util:hash',
        '//components/util:coding',
    ],
)
